services:
  postgres:
    image: postgres:17
    container_name: p3-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - p3-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    container_name: p3-redis

    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - p3-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: p3-app

    ports:
      - "${APP_PORT}:8080"

    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_SSL: ${REDIS_SSL}
      AWS_PROFILE: p3-dev
      AWS_REGION: ap-northeast-2
      COGNITO_ISSUER_URI: ${COGNITO_ISSUER_URI}
      P3_CORS_ALLOWED_ORIGINS: ${P3_CORS_ALLOWED_ORIGINS}
      P3_WEBSOCKET_ALLOWED_ORIGINS: ${P3_WEBSOCKET_ALLOWED_ORIGINS}
      P3_DELIVERY_BASE_URL: ${P3_DELIVERY_BASE_URL}
    depends_on:
      redis:
        condition: service_healthy



volumes:
  p3-postgres-data:
  p3-redis-data:
