package io.point3.p3api.operator.domain.type;

public enum OperatorActionType {
  USER_STATUS_CHANGED,
  STORE_STATUS_CHANGED,
  GALLERY_ITEM_STATUS_CHANGED,
  SELLER_ONBOARDING_HELD,
  REPORT_REVIEWED,
  REPORT_RESOLVED,
  SERVICE_INQUIRY_ASSIGNED,
  SERVICE_INQUIRY_ANSWERED,
  SERVICE_INQUIRY_CLOSED
}
