spring:
  application:
    name: p3-api

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:p3}
    username: ${POSTGRES_USER:p3}
    password: ${POSTGRES_PASSWORD:p3}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: dummy
        secret-key: dummy
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
p3:
  websocket:
    allowed-origins: ${P3_WEBSOCKET_ALLOWED_ORIGINS}

  asset:
    storage:
      original-asset-bucket: p3-s3-original-dev
      processed-asset-bucket: p3-s3-processed-dev
    delivery:
      base-url: ${P3_DELIVERY_BASE_URL:}
