package io.point3.p3api.notification.domain.type;

public enum NotificationType {
  ORDER_FORM_SUBMITTED,
  ORDER_FORM_UPDATED,
  ORDER_CONFIRMATION_SENT,
  ORDER_CONFIRMATION_UPDATED,
  INQUIRY_CREATED,
  INQUIRY_REPLIED,
  PAYMENT_COMPLETED,
  ORDER_STATUS_CHANGED,
  ORDER_CANCEL_REQUESTED,
  ORDER_REFUNDED,
  ORDER_REFUND_FAILED
}
